Q 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.



In [1]:
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))
print("Original Array:")
print(array)

# Interchange rows and columns (transpose the array)
transposed_array = array.T
print("\nTransposed Array:")
print(transposed_array)

Original Array:
[[99 55 56]
 [ 5 21 69]
 [86 58 71]]

Transposed Array:
[[99  5 86]
 [55 21 58]
 [56 69 71]]


Q 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.



In [2]:
import numpy as np

# Generate a 1D array with 10 elements (for example, from 1 to 10)
array_1d = np.arange(1, 11)
print("1D Array:")
print(array_1d)

# Reshape the array into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("\nReshaped to 2x5 Array:")
print(array_2x5)

# Reshape the array into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)
print("\nReshaped to 5x2 Array:")
print(array_5x2)

1D Array:
[ 1  2  3  4  5  6  7  8  9 10]

Reshaped to 2x5 Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Reshaped to 5x2 Array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


Q 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.



In [3]:
import numpy as np

# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)
print("Original 4x4 Array:")
print(array_4x4)

# Add a border of zeros to create a 6x6 array
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 Array with Zero Border:")
print(array_6x6)


Original 4x4 Array:
[[0.36532453 0.82119551 0.68251371 0.75051417]
 [0.35223521 0.99186035 0.48565551 0.81942248]
 [0.71631324 0.86960913 0.5868079  0.95094045]
 [0.99495576 0.77737228 0.51892779 0.55403543]]

6x6 Array with Zero Border:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.36532453 0.82119551 0.68251371 0.75051417 0.        ]
 [0.         0.35223521 0.99186035 0.48565551 0.81942248 0.        ]
 [0.         0.71631324 0.86960913 0.5868079  0.95094045 0.        ]
 [0.         0.99495576 0.77737228 0.51892779 0.55403543 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


Q 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [4]:
import numpy as np

# Create an array from 10 to 60 with a step of 5
array = np.arange(10, 65, 5)
print("Array from 10 to 60 with step 5:")
print(array)

Array from 10 to 60 with step 5:
[10 15 20 25 30 35 40 45 50 55 60]


Q 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.



In [5]:
import numpy as np

# Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Apply uppercase transformation
uppercase_array = np.char.upper(array)
print("Uppercase:")
print(uppercase_array)

# Apply lowercase transformation
lowercase_array = np.char.lower(array)
print("\nLowercase:")
print(lowercase_array)

# Apply title case transformation
titlecase_array = np.char.title(array)
print("\nTitle Case:")
print(titlecase_array)

Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
['python' 'numpy' 'pandas']

Title Case:
['Python' 'Numpy' 'Pandas']


Q 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.



In [6]:
import numpy as np

# Create a NumPy array of words
words_array = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_words_array = np.char.join(' ', words_array)
print("Words with spaces between characters:")
print(spaced_words_array)

Words with spaces between characters:
['p y t h o n' 'n u m p y' 'p a n d a s']


Q 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.



In [7]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

# Element-wise addition
addition = array1 + array2
print("\nElement-wise Addition:")
print(addition)

# Element-wise subtraction
subtraction = array1 - array2
print("\nElement-wise Subtraction:")
print(subtraction)

# Element-wise multiplication
multiplication = array1 * array2
print("\nElement-wise Multiplication:")
print(multiplication)

# Element-wise division
division = array1 / array2
print("\nElement-wise Division:")
print(division)

Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise Division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


Q 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.



In [8]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:")
print(identity_matrix)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)

5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


Q 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.



In [9]:
import numpy as np

# Function to check if a number is prime
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(np.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True

# Generate an array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1000, 100)
print("Random Array:")
print(random_array)

# Find prime numbers in the array
prime_numbers = np.array([num for num in random_array if is_prime(num)])
print("\nPrime Numbers in the Array:")
print(prime_numbers)

Random Array:
[610 778 855 523 240 340 259 653 206 231  72 168 276 985 243 989 626 970
 770 713 564 851 382 648 349 567 907 781 809 729 756 924 711 339 157 615
 268 273 388 943 722 100 513 350  76 152 722 584 798 800 369 108 719 830
 716 311 462  10 336 993 155 163 917 216 528 359  21  50 191 353 880 990
 181 326 120 156 218  86 444 105 348 644 191 687 875 560  42  58 788 758
 715 400 424 100   5 104 522 914 572 744]

Prime Numbers in the Array:
[523 653 349 907 809 157 719 311 163 359 191 353 181 191   5]


Q 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.


In [12]:
# Correcting the calculation of weekly averages
# Generate random temperatures for a month (30 days)
daily_temperatures = np.random.uniform(low=15, high=30, size=30)

# Calculate weekly averages for the first 28 days (4 weeks)
weekly_averages = daily_temperatures[:28].reshape(-1, 7).mean(axis=1)

daily_temperatures, weekly_averages

(array([18.96833418, 26.61350534, 21.84225498, 23.52650923, 15.28184701,
        24.26453246, 24.18143584, 24.25400995, 29.15622118, 25.22730449,
        20.39261851, 21.55547931, 25.46446794, 15.90338207, 25.00150073,
        25.05956804, 18.15573842, 16.93389446, 19.73142526, 20.45566156,
        23.55295156, 21.5790227 , 29.82560757, 16.53067216, 18.13315134,
        17.41964277, 24.79662488, 18.79937404, 21.99466159, 18.66638388]),
 array([22.09691701, 23.13621192, 21.27010572, 21.01201364]))